name:                rgrammar
version:             0.1.0.0
github:              "ValeBini/TP-ALP"
license:             GNU3
author:              Valentina Bini
maintainer:          "example@example.com"
copyright:           "2020 ValeBini"

extra-source-files:
- README.md
- ChangeLog.md

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on GitHub at <https://github.com/githubuser/rgrammar#readme>

dependencies:
- base >= 4.7 && < 5
- containers
- array >= 0.5.4.0
- pretty >= 1.1.3.6
- readline >= 1.0.3.0

library:
  source-dirs: src

executables:
  rgrammar:
    main:                Main.hs
    source-dirs:         app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - rgrammar

tests:
  rgrammar-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - rgrammar
